# Mod Configuration
mod_name=Fix Alt Gr
mod_id=fixaltgr
mod_version=1.0.0
mod_description=Fixes the MC-127862 bug where pressing Alt Gr locks the Left Control key.
mod_license=LGPL-3.0-only
mod_authors=KRW_CLASSIC, Mikolaj_Kolek

# Gradle Configuration
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureoncommand=true
org.gradle.workers.max=8
org.gradle.jvmargs=-Xmx8G
