modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/KRWCLASSIC/alt-greatness/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "fixaltgr"
version = "${file.jarVersion}"
displayName = "${name}"
authors = "${authors}"
displayURL = "https://modrinth.com/mod/alt-greatness"
description = '''
${description}
'''
logoFile = "assets/fixaltgr/icon.png"

[[dependencies.fixaltgr]]
    modId="minecraft"
    mandatory=true
    versionRange="${mcVersionForge}"
    ordering="NONE"
    side="BOTH"
